services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "file:./prisma/dev.db"
    volumes:
      - prisma_generated:/app/node_modules/.prisma # Consistent path
    command: |+
      sh -c "
        mkdir -p /app/prisma &&
        touch /app/prisma/dev.db &&
        bunx prisma migrate deploy &&
        bunx prisma generate
      "
        
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    volumes:
      - prisma_generated:/usr/src/app/node_modules/.prisma
    env_file: ./apps/api/.env
    ports:
      - "3000:3000"
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  smtp:
    build:
      context: .
      dockerfile: apps/smtp/Dockerfile
    environment:
      SMTP_PORT: 25
      GMAIL_USER: nischalm3pro@gmail.com
      GMAIL_APP_PASSWORD: ncmh bchh sipe heim
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "25:25"
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - prisma_generated:/usr/src/app/node_modules/.prisma
    restart: unless-stopped

  ui:
    build:
      context: ./apps/ui
      dockerfile: Dockerfile.node
    ports:
      - "5173:3000"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # use prod 
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    depends_on:
      - api
      - ui
    restart: unless-stopped

volumes:
  prisma_generated:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
