services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: file:./dev.db
    command: |
      sh -c "
        echo 'Running migrations...' &&
        bunx prisma migrate deploy &&
        echo 'Generating Prisma client...' &&
        bunx prisma generate &&
        echo 'Seeding database...' &&
        bun run prisma/seed.ts
      "
    volumes:
      - prisma_generated:/app/generated # Share generated files

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file: ./apps/api/.env
    ports:
      - "3000:3000"
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - prisma_generated:/usr/src/app/node_modules/.prisma
    restart: unless-stopped

  smtp:
    build:
      context: .
      dockerfile: apps/smtp/Dockerfile
    environment:
      SMTP_PORT: 25
      GMAIL_USER: nischalm3pro@gmail.com
      GMAIL_APP_PASSWORD: ncmh bchh sipe heim
    ports:
      - "25:25"
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - prisma_generated:/usr/src/app/node_modules/.prisma
    restart: unless-stopped

  ui:
    build:
      context: ./apps/ui
      dockerfile: Dockerfile.node
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  prisma_generated:
    driver: local
